[2022-08-23 00:00:33,447] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.process_user scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:33,491] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.process_user scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:33,493] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:33,494] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 00:00:33,495] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:33,567] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): process_user> on 2022-08-22 00:00:00+00:00
[2022-08-23 00:00:33,576] {standard_task_runner.py:52} INFO - Started process 92793 to run task
[2022-08-23 00:00:33,603] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmprqx5_kn5', '--error-file', '/tmp/tmpdh9j0zxb']
[2022-08-23 00:00:33,610] {standard_task_runner.py:80} INFO - Job 14: Subtask process_user
[2022-08-23 00:00:33,857] {task_command.py:371} INFO - Running <TaskInstance: user_processing.process_user scheduled__2022-08-22T00:00:00+00:00 [running]> on host 6eab8cd56147
[2022-08-23 00:00:34,114] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-08-23 00:00:34,417] {python.py:173} INFO - Done. Returned value was: None
[2022-08-23 00:00:34,500] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=process_user, execution_date=20220822T000000, start_date=20220823T000033, end_date=20220823T000034
[2022-08-23 00:00:34,656] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-23 00:00:34,869] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
