[2022-08-23 00:00:08,004] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:08,024] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:08,026] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:08,030] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 00:00:08,032] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:08,096] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-08-22 00:00:00+00:00
[2022-08-23 00:00:08,115] {standard_task_runner.py:52} INFO - Started process 92682 to run task
[2022-08-23 00:00:08,126] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmpoao68lxd', '--error-file', '/tmp/tmpbbhh_z7l']
[2022-08-23 00:00:08,132] {standard_task_runner.py:80} INFO - Job 12: Subtask is_api_available
[2022-08-23 00:00:08,427] {task_command.py:371} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-08-22T00:00:00+00:00 [running]> on host 6eab8cd56147
[2022-08-23 00:00:08,681] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-08-23 00:00:08,685] {http.py:97} INFO - Poking: api/
[2022-08-23 00:00:08,713] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-08-23 00:00:08,719] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-08-23 00:00:10,715] {base.py:301} INFO - Success criteria met. Exiting.
[2022-08-23 00:00:10,749] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220822T000000, start_date=20220823T000008, end_date=20220823T000010
[2022-08-23 00:00:10,826] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-23 00:00:10,947] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
